services:
  db:
    container_name: DB
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPW}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPW}
      MYSQL_DATABASE: contentdb
    ports:
      - ${DB_PORT}:3306
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 30s
          retries: 10
    networks:
      - backend

  backend:
    container_name: Backend
    build: ./ContentManagement
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend
      - backend
    restart: on-failure

  frontend:
    container_name: Frontend
    build: ./frontend
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - frontend
      - backend
    restart: on-failure

networks:
  backend:
    internal: true
  frontend:
