version: "3.8"
services:
  db:
    container_name: DB
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPW}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
    ports:
      - ${MYSQL_PORT}:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
      retries: 40
    networks:
      - internal
    volumes:
      - ./database/db:/var/lib/mysql

  dataservice:
    container_name: dataservice
    build:
      context: ./
      dockerfile: ./cmd/dataservice/dockerfile
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public
      - internal
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./cmd/frontend/dockerfile
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - dataservice
    networks:
      - public
      - internal
    restart: on-failure

networks:
  internal:
    internal: true
  public:
