
FROM golang:1.21-alpine3.19 as builder
COPY . /app
WORKDIR /app
RUN go mod tidy
RUN go build -o /bin/app/frontendexe ./cmd/frontend

FROM scratch
COPY --from=builder /bin/app /app
COPY --from=builder /app/frontend /app/frontend
WORKDIR /app
CMD ["/app/frontendexe"]