// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

// TODO enable State of user sign in
func MainNavbar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar grow-0 h-[50px] flex flex-row justify-between items-center px-10 bg-primary-800\"><div class=\"logo-section\"><a class=\"clickableEl flex flex-row justify-between items-center\" title=\"Home\" href=\"/\"><img src=\"/assets/Logo.svg\" alt=\"Logo Goes here\"><h3 class=\"font-h3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `ThreatTrack`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h3></a></div><div id=\"searchBar\" class=\"flex items-center bg-primary-900 p-2 border-primary-900 border-solid border rounded-md w-1/3 h-2/3 hover:border-secondary-700\"><input type=\"text\" class=\"bg-inherit border-none focus:ring-0 block w-full h-2/3 placeholder:text-font-900\" placeholder=\"Search for something...\"></div><div class=\"vertical-container actionBar\"><button class=\"clickableEl flex justify-center items-center\" title=\"Dashboard\" hx-get=\"/dashboard/\" hx-target=\"#contentBody\"><img src=\"/assets/dashboard.svg\" alt=\"Dashboard\"></button> <button class=\"clickableEl flex justify-center items-center\" title=\"Incidents\" hx-get=\"/incidentTable/\" hx-target=\"#contentBody\"><img src=\"/assets/Incidents.svg\" alt=\"Incidents\"></button> <button class=\"clickableEl flex justify-center items-center\" title=\"Indicators\" hx-get=\"/indicatorTable/\" hx-target=\"#contentBody\"><img src=\"/assets/Indicator.svg\" alt=\"IOCs\"></button> <button class=\"clickableEl flex justify-center items-center\" title=\"Settings\" hx-get=\"/settings/\" hx-target=\"#contentBody\"><img src=\"/assets/settings.svg\" alt=\"Settings\"></button> <button class=\"clickableEl flex justify-center items-center\" title=\"LogOut\" hx-get=\"/logout\" hx-target=\"#contentBody\"><img src=\"/assets/logout.svg\" alt=\"Logout\"></button></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
