
FROM golang:1.21-alpine3.19 as builder
COPY . /app
WORKDIR /app
RUN go mod tidy
RUN go build -o /bin/app/dataserviceexe ./cmd/dataservice

FROM scratch
COPY --from=builder /bin/app /app
COPY --from=builder /app/dataservice /app/dataservice
WORKDIR /app
CMD ["/app/dataserviceexe"]