// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package incidentviews

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/pulsone21/threattrack/lib/entities"
import "github.com/pulsone21/threattrack/frontend/templates/incidentviews/components"
import "github.com/pulsone21/threattrack/frontend/templates/components"

func IncWorklogPage(inc entities.Incident, wl []entities.Worklog) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"inc-grid font-body\" style=\"height: calc(100vh - 72px);\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = incComponents.IncHeader(inc.Name, "Worklogs").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = incComponents.IncNavbar(inc.Id.String()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"inc-grid-el grid_rs2re6_cs2ce4 \"><p class=\"font-h4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `Worklogs`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><ul class=\"worklog-list\" style=\"max-height: 95%; overflow:auto;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, w := range wl {
			templ_7745c5c3_Err = components.Worklog(w).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</ul></div><div class=\"grid_rs4re6_cs1_ce2 inc-grid-el inc-grid-actionbar\"><button class=\"clickableEl\" title=\"Summary View\"><img style=\"width: 35px; height: 35px;\" src=\"/assets/inc_home.svg\" alt=\"Summary View\"></button> <button class=\"clickableEl\" title=\"Worklogs\"><img style=\"width: 35px; height: 35px;\" src=\"/assets/feed.svg\" alt=\"Worklogs\"></button> <button class=\"clickableEl\" title=\"Planning\"><img style=\"width: 35px; height: 35px;\" src=\"/assets/planing.svg\" alt=\"Planning\"></button> <button class=\"clickableEl\" title=\"IOC View\"><img style=\"width: 35px; height: 35px;\" src=\"/assets/IOCView.svg\" alt=\"IOC View\"></button></div><div class=\"inc-grid-el grid_rs2re6_cs4ce6\" style=\"display: flex; flex-direction: row; justify-content: space-between;\"><div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `Preview`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
